spring:
  application:
    name: konnect-starter-example

konnect:
  api:
    base-url: https://api.sandbox.konnect.network/api/v2/
    key: ${KONNECT_KEY}
    receiver-wallet-id: ${KONNECT_RECEIVER_WALLET_ID}



springdoc:
  api-docs:
    path: /api-docs/v3
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true
  default-produces-media-type: application/json
