spring:
  application:
    name: konnect-starter-example

konnect:
  api:
    base-url: https://api.sandbox.konnect.network/api/v2/
    key: ${KONNECT_KEY}
    receiver-wallet-id: ${KONNECT_RECEIVER_WALLET_ID}
    webhook-url: http://localhost:8080/api/konnect/webhook


resilience4j:
  # --- Rate Limiter Configuration ---
  ratelimiter:
    instances:
      konnect-api:
        limit-for-period: 95            # Stay safely below Konnect's 100 request/minute limit
        limit-refresh-period: 60s       # The period is 1 minute
        timeout-duration: 2s            # How long a thread will wait for a permit

  # --- Automatic Retry Configuration ---
  retry:
    instances:
      konnect-api:
        max-attempts: 3                 # Try the original call + 2 retries
        wait-duration: 500ms            # Initial wait time before the first retry
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2 # Wait times: 500ms -> 1s -> 2s
        # This predicate ensures we only retry on 5xx server errors, not 4xx client errors
        retry-exception-predicate: io.github.oussemasahbeni.konnect.autoconfigure.KonnectRetryExceptionPredicate

springdoc:
  api-docs:
    path: /api-docs/v3
  swagger-ui:
    path: /docs
    operationsSorter: method
    display-request-duration: true
  default-produces-media-type: application/json
