name: Continuous Integration

on:
  pull_request:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # The 'verify' phase runs all tests and checks without deploying
      - name: Build and run tests
        run: mvn -B clean verify