name: "Publish Artifact"

on:
  push:
    branches:
      - main
    # tags:
    #  - 'v*'

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    name: Publish artifact via The Central Portal
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


      - name: Deploy to Maven Central
        run: mvn clean deploy -P release -s ci-settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN}}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            konnect-spring-boot-starter/target/*.jar
            konnect-spring-boot-starter/target/*.pom